// Add Product
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

// Update product
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

// Get product by Type
export const GET_PRODUCT_BY_CATEGORY_REQUEST = 'GET_PRODUCT_BY_CATEGORY_REQUEST';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = 'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAILED = 'GET_PRODUCT_BY_CATEGORY_FAILED';

// Get wishlist products
export const GET_WISHLIST_PRODUCT_REQUEST = 'GET_WISHLIST_PRODUCT_REQUEST';
export const GET_WISHLIST_PRODUCT_SUCCESS = 'GET_WISHLIST_PRODUCT_SUCCESS';
export const GET_WISHLIST_PRODUCT_FAILED = 'GET_WISHLIST_PRODUCT_FAILED';

//Del wishlist product
export const DEL_WISHLIST_PRODUCT_REQUEST = 'DEL_WISHLIST_PRODUCT_REQUEST';
export const DEL_WISHLIST_PRODUCT_SUCCESS = 'DEL_WISHLIST_PRODUCT_SUCCESS';
export const DEL_WISHLIST_PRODUCT_FAILED = 'DEL_WISHLIST_PRODUCT_FAILED';

// Get my Ads products
export const GET_ADS_PRODUCT_REQUEST = 'GET_ADS_PRODUCT_REQUEST';
export const GET_ADS_PRODUCT_SUCCESS = 'GET_ADS_PRODUCT_SUCCESS';
export const GET_ADS_PRODUCT_FAILED = 'GET_ADS_PRODUCT_FAILED';

//Delete my Ads product
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'

// Set favorite
export const SET_FAVORITE_REQUEST = 'SET_FAVORITE_REQUEST';
export const SET_FAVORITE_SUCCESS = 'SET_FAVORITE_SUCCESS';
export const SET_FAVORITE_FAILED = 'SET_FAVORITE_FAILED';

// Add viewed count
export const ADD_VIEW_COUNT_REQUEST = 'ADD_VIEW_COUNT_REQUEST';
export const ADD_VIEW_COUNT_SUCCESS = 'ADD_VIEW_COUNT_SUCCESS';
export const ADD_VIEW_COUNT_FAILED = 'ADD_VIEW_COUNT_FAILED';

// Search product
export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILED = 'SEARCH_PRODUCT_FAILED';

// Send Report
export const SEND_REPORT_REQUEST = 'SEND_REPORT_REQUEST'
export const SEND_REPORT_SUCCESS = 'SEND_REPORT_SUCCESS'
export const SEND_REPORT_FAILED = 'SEND_REPORT_FAILED'