// Add Product
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

// Get product by Type
export const GET_PRODUCT_BY_CATEGORY_REQUEST = 'GET_PRODUCT_BY_CATEGORY_REQUEST';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = 'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAILED = 'GET_PRODUCT_BY_CATEGORY_FAILED';

// Get wishlist products
export const GET_WISHLIST_PRODUCT_REQUEST = 'GET_WISHLIST_PRODUCT_REQUEST';
export const GET_WISHLIST_PRODUCT_SUCCESS = 'GET_WISHLIST_PRODUCT_SUCCESS';
export const GET_WISHLIST_PRODUCT_FAILED = 'GET_WISHLIST_PRODUCT_FAILED';

//Del wishlist product
export const DEL_WISHLIST_PRODUCT_REQUEST = 'DEL_WISHLIST_PRODUCT_REQUEST';
export const DEL_WISHLIST_PRODUCT_SUCCESS = 'DEL_WISHLIST_PRODUCT_SUCCESS';
export const DEL_WISHLIST_PRODUCT_FAILED = 'DEL_WISHLIST_PRODUCT_FAILED';

// Get my Ads products
export const GET_ADS_PRODUCT_REQUEST = 'GET_ADS_PRODUCT_REQUEST';
export const GET_ADS_PRODUCT_SUCCESS = 'GET_ADS_PRODUCT_SUCCESS';
export const GET_ADS_PRODUCT_FAILED = 'GET_ADS_PRODUCT_FAILED';