export const SEND_DIRECT_MESSAGE_REQUEST = 'SEND_DIRECT_MESSAGE_REQUEST'
export const SEND_DIRECT_MESSAGE_SUCCESS = 'SEND_DIRECT_MESSAGE_SUCCESS'
export const SEND_DIRECT_MESSAGE_FAILED = 'SEND_DIRECT_MESSAGE_FAILED'

export const GET_CHAT_USER_REQUEST = 'GET_CHAT_USER_REQUEST'
export const GET_CHAT_USER_SUCCESS = 'GET_CHAT_USER_SUCCESS'
export const GET_CHAT_USER_FAILED = 'GET_CHAT_USER_FAILED'

export const GET_CHAT_DATA_REQUEST = 'GET_CHAT_DATA_REQUEST'
export const GET_CHAT_DATA_SUCCESS = 'GET_CHAT_DATA_SUCCESS'
export const GET_CHAT_DATA_FAILED = 'GET_CHAT_DATA_FAILED'

export const SEND_AD_REQUEST =  'SEND_AD_REQUEST'
export const SEND_AD_SUCCESS = 'SEND_AD_SUCCESS'
export const SEND_AD_FAILED = 'SEND_AD_FAILED'

export const GET_AD_SUBJECT_REQUEST = 'GET_AD_SUBJECT_REQUEST'
export const GET_AD_SUBJECT_SUCCESS = 'GET_AD_SUBJECT_SUCCESS'
export const GET_AD_SUBJECT_FAILED = 'GET_AD_SUBJECT_FAILED'
