// Get user token
export const GET_PACKAGE_REQUEST = 'GET_PACKAGE_REQUEST';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const GET_PACKAGE_FAILED = 'GET_PACKAGE_FAILED';

// Get My package
export const GET_MY_PACKAGE_REQUEST = 'GET_MY_PACKAGE_REQUEST';
export const GET_MY_PACKAGE_SUCCESS = 'GET_MY_PACKAGE_SUCCESS';
export const GET_MY_PACKAGE_FAILED = 'GET_MY_PACKAGE_FAILED';

// Get Telr web url
export const GET_WEBURL_REQUEST = 'GET_WEBURL_REQUEST'
export const GET_WEBURL_SUCCESS = 'GET_WEBURL_SUCCESS'
export const GET_WEBURL_FAILED = 'GET_WEBURL_FAILED'

// Check user's payment status
export const CHECK_PAYMENT_STATUS_REQUEST = 'CHECK_PAYMENT_STATUS_REQUEST'
export const CHECK_PAYMENT_STATUS_SUCCESS = 'CHECK_PAYMENT_STATUS_SUCCESS'
export const CHECK_PAYMENT_STATUS_FAILED = 'CHECK_PAYMENT_STATUS_FAILED'

// Get bank details
export const GET_BANK_DETAIL_REQUEST = 'GET_BANK_DETAIL_REQUEST'
export const GET_BANK_DETAIL_SUCCESS = 'GET_BANK_DETAIL_SUCCESS'
export const GET_BANK_DETAIL_FAILED = 'GET_BANK_DETAIL_FAILED'

// Send bank details
export const SEND_BANK_DETAIL_REQUEST = 'SEND_BANK_DETAIL_REQUEST'
export const SEND_BANK_DETAIL_SUCCESS = 'SEND_BANK_DETAIL_SUCCESS'
export const SEND_BANK_DETAIL_FAILED = 'SEND_BANK_DETAIL_FAILED'